services:
  - type: web
    name: smartfinance-backend
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt && python ingest_data.py"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: USE_MOCK_AI
        value: true
      - key: ENVIRONMENT
        value: production
      - key: PYTHON_VERSION
        value: 3.11.9
